#!/bin/sh

set -e

case $1 in
   config)
        cat <<'EOM'
graph_title Statistics
graph_info Prints a bunch of statistical information
graph_category wobble
requests_time.type DERIVE
requests_time.graph no
requests.type DERIVE
requests.graph no
avg_time.label Average Time
avg_time.cdef requests_time,requests,/
EOM
        exit 0;;
esac

if [ -z "$WOBBLE_HOME" ]; then
  printf "ERROR: No WOBBLE_HOME set.\n"
  exit 1
fi

printf "requests.value "
$WOBBLE_HOME/scripts/get-stats.php "requests.counter"
printf "requests_time.value "
$WOBBLE_HOME/scripts/get-stats.php "requests.time"
