#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Online users
graph_info Prints the currently logged in users into wobble
graph_category wobble
graph_vlabel users online
users.label users
sessions.label sessions
EOM
        exit 0;;
esac

if [ -z "$WOBBLE_HOME" ]; then
  echo "ERROR: No WOBBLE_HOME set."
  exit 1
fi

echo -n "users.value "
$WOBBLE_HOME/scripts/get-online-users.php
echo -n "sessions.value "
$WOBBLE_HOME/scripts/get-online-users.php --sessions
