#!/bin/sh

set -e

case $1 in
   config)
        cat <<'EOM'
graph_title Warnings
graph_info Several sensors
graph_category wobble
graph_vlabel warnings
orphaned_topics.label Orphaned Topics
orphaned_topics.warning 1
orphaned_topics.critical 10
orphaned_posts.label Orphaned Posts
orphaned_posts.warning 1
orphaned_posts.critical 10
EOM
        exit 0;;
esac

if [ -z "$WOBBLE_HOME" ]; then
  printf "ERROR: No WOBBLE_HOME set.\n"
  exit 1
fi

printf "orphaned_topics.value "
$WOBBLE_HOME/bin/wobble warning-sensors --orphaned-topics
printf "orphaned_posts.value "
$WOBBLE_HOME/bin/wobble warning-sensors --orphaned-posts
