#!/bin/sh

set -e

case $1 in
   config)
        cat <<'EOM'
graph_title Online users
graph_info Prints the currently logged in users into wobble
graph_category wobble
graph_vlabel users online
users.label users
sessions.label sessions
EOM
        exit 0;;
esac

if [ -z "$WOBBLE_HOME" ]; then
  printf "ERROR: No WOBBLE_HOME set.\n"
  exit 1
fi

printf "users.value "
$WOBBLE_HOME/bin/wobble get-online-users
printf "sessions.value "
$WOBBLE_HOME/bin/wobble get-online-users --sessions
