#!/bin/sh

set -e

case $1 in
   config)
        cat <<'EOM'
graph_title Requests Total 
graph_info Prints a bunch of statistical information
graph_category wobble
graph_period minute
requests.label Number of Requests
requests.min 0
requests.type DERIVE
requests.
success.label Successfull calls
success.min 0
success.type DERIVE
errors.label Failed calls
errors.min 0
errors.type DERIVE

EOM
        exit 0;;
esac

if [ -z "$WOBBLE_HOME" ]; then
  printf "ERROR: No WOBBLE_HOME set.\n"
  exit 1
fi

printf "requests.value "
$WOBBLE_HOME/bin/wobble get-stats "requests.counter"
printf "success.value "
$WOBBLE_HOME/bin/wobble get-stats "jsonrpc.success"
printf "errors.value "
$WOBBLE_HOME/bin/wobble get-stats "jsonrpc.errors"
