#!/bin/sh

set -e

case $1 in
   config)
        cat <<'EOM'
graph_title Request Time
graph_info Whats the average time of the current requests
graph_category wobble
graph_period minute
requests_time.label Request Time
requests_time.type DERIVE
requests_time.graph no
requests.label Number of Requests
requests.type DERIVE
requests.graph no
avg_time.label Average Time (Current)
avg_time.cdef requests_time,requests,/
EOM
        exit 0;;
esac

if [ -z "$WOBBLE_HOME" ]; then
  printf "ERROR: No WOBBLE_HOME set.\n"
  exit 1
fi

printf "requests.value "
$WOBBLE_HOME/bin/wobble get-stats "requests.counter"
printf "requests_time.value "
$WOBBLE_HOME/bin/wobble get-stats "requests.time"
printf "avg_time.value 0\n"
exit 0
